" set guifont=Monospace\ 14
set guifont=Monaco:h21
set list
set number
set go-=T

:syntax on
filetype plugin indent on

augroup myfiletypes
  " Clear old autocmds in group
  autocmd!
   " autoindent with two spaces, always expand tabs
  autocmd FileType ruby,haml,eruby,yaml set ai sw=2 sts=2 et
  autocmd BufNewFile,BufRead *.json_builder setf ruby
  autocmd BufNewFile,BufRead *.red setf ruby
augroup END

au BufNewFile,BufRead *.erl set ai sw=4 sts=4 et

set ai
set sts=2
set sw=2
set autoindent
set smarttab

set bg=dark

:colorscheme vividchalk

" window splitting mappings
nmap <leader>v :vsplit<CR> <C-w><C-w>
nmap <leader>s :split<CR> <C-w><C-w>

" nerd tree
map <leader>d :execute 'NERDTreeToggle ' . getcwd()<CR>
