#!/usr/bin/env ruby

# written by Tammer Saleh
# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [ 
#  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/scrooloose/nerdcommenter.git",
#  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/oscarh/vimerl.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
#  "git://github.com/tsaleh/vim-align.git",
#  "git://github.com/tsaleh/vim-supertab.git",
#  "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/scrooloose/syntastic.git",
  "git://github.com/nelstrom/vim-mac-classic-theme.git",
  "git://github.com/Raimondi/delimitMate.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/vim-scripts/greplace.vim.git",
  "git://github.com/hallettj/jslint.vim.git",
  "git://github.com/altercation/vim-colors-solarized.git"
]

vim_org_scripts = [
#  ["IndexedSearch", "7062",  "plugin"],
#  ["gist",          "12732", "plugin"],
  ["jquery",          "12107",  "syntax"],
  ["minibufexpl",     "3640",   "plugin"],
  ['json',            "10853",  "syntax"]
#  ["vimclojure",      "11066",  "plugin"]
]

# TODO add support for bitbucket mercurial repos
bitbucket_bundles = [
  "https://bitbucket.org/kotarak/vimclojure/get/tip.tar.gz"
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

# TODO add support for updating these bundles
exclude_bundles = [
                    'vimclojure',
                    'vim-peepopen',
                    'vim-latex-1.8.23-20101027-r1112'
                  ]

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each { |d| FileUtils.rm_rf(d) unless exclude_bundles.include?(d) }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
